security:
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            oauth:
                resource_owners:
                    github: "/login/check-github"
                login_path: /login
                failure_path: /login

                oauth_user_provider:
                    # This is a custom user provider, created from FOSUBUserProvider - will manage the
                    # automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: gruik.user.security.user_provider
            logout: true
            anonymous: true

    access_control:
        - { path: ^/(login|connect), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
