parameters:
    app_bundle.security.user_provider.class: AppBundle\Security\FOSUBUserProvider

services:
    app_bundle.security.user_provider:
        class: "%app_bundle.security.user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments:
            - '@fos_user.user_manager'
            - { github: github_id }

    app_bundle.controllers.main:
        class: AppBundle\Controller\DefaultController
        calls:
            - [ setContainer, [ @service_container ] ]
